### ISSUE TITLE
Funding for OSD Summit

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/organization#64] opened 2017-03-02 18:48 UTC
I don't want to get the conversation about funding for an Open Source Design Summit to get lost in the excitement of #57.

To make it all as open as possible, let's try to keep that conversation in one place. Transparency is useless if it's not clear.

There's been a couple of things suggested so far:

* Funding from OpenCollective (suggested putting aside 50%-75% of funding there). 
* Asking specific organizations for funding:
    * Wikimedia (see https://github.com/opensourcedesign/organization/issues/57#issuecomment-283711177)
    * Mozilla (see https://github.com/opensourcedesign/organization/issues/57#issuecomment-283639844)
    * Others? 
* Encourage a donation of €50.00 every time someone posts an OSD job on the job board.
* A GoFundMe drive.

Let's use this thread to keep track of where we've submitted requests for funding, etc. 

The first step is probably figuring out how much something like this would cost. 

* Venue rental costs: discussed in #59. Looks like we can probably get this for free. 
* Accommodation costs: can we house everyone with locals? Or rent a biggish space for a week? Can we try to do so via an open source platform like Trustroots?
* Food? I'm fine with this being everyone fends for themselves.
* Travel costs? How many people can we reimburse travel-wise? This seems like the main cost to me, but can also vary a lot. (For me personally the biggest issue is timing rather than actual travel costs). We should set a target (who's going to attend, where are they coming from?) and then figure out a way of fairly re-imbursing them if we can get funding.

**Comment by elioqoshi** [comment] 2017-03-02 20:04
Venue will be free or quite cheap indeed.
I'd rather try to find a single place for accommodation as it's way more fun to stay at the same place rather than everyone being in different places. We could book a whole hostel or AirBnB for us even. Would be also quite affordable. 

Regarding travel costs, it would help immensely if we can be sponsored by our own companies and list them as sponsors of the Summit. So we would have some budget put aside for contributors who might need it more.

Regarding food, we could centralize dinners and maybe even breakfast from a single budget.

Let's keep this going!

**Comment by ei8fdb** [comment] 2017-03-03 08:55
> it would help immensely if we can be sponsored by our own companies and list them as sponsors of the Summit. 

You assume we all work for 1) companies, 2) who "get" open source and 3) design. :)

**Comment by elioqoshi** [comment] 2017-03-03 09:32
I didn't. That's why I said IF. No need to read between the lines. 
The fact that some of us can be sponsored is also beneficial to those who aren't sponsored, as we can set budget aside for them.

**Comment by belenbarrospena** [comment] 2017-03-03 12:19
I will happily self fund if the event is in Berlin. I can cover my own
travel, accommodation and sustenance. And whatever @ei8fdb says, he will be
happy to cover his own expenses too ;)

**Comment by Kriesse** [comment] 2017-03-03 16:40
Github has been quite helpful with travel / ticket sponsorships for CSSconf EU. They have an application form: https://community.github.com/

**Comment by elioqoshi** [comment] 2017-03-03 16:49
I haven't had luck for the 3 last editions of OSCAL with GitHub as a sponsor :/ Not sure where their focus is. Wouldn't hurt to try it of course

**Comment by evalica** [comment] 2017-10-09 11:01
Duplicate of https://github.com/opensourcedesign/organization/issues/97

**Comment by jancborchardt** [comment] 2017-10-10 19:31
The funding we get from Wikimedia thanks to @Incabell basically takes care of all of this. Since it’s a comment at https://github.com/opensourcedesign/organization/issues/97#issuecomment-335115032 (the issue @evalica also linked) I’ll close this here. :)

**Closed by jancborchardt** 2017-10-10 19:31 UTC
Labels: summit
