### ISSUE TITLE
overview of problems, chances and practices of integrating UX and Open Source Software development (ideally based on research)

### ISSUE THREAD

**Issue by jdittrich** [opensourcedesign/organization#74] opened 2017-03-17 08:58 UTC
**Story:** As an opensourcedesigner, I want to know which problems and perks designers can expect in FOSS projects and what the strategies are of dealing with it.

**Problem:** We currently lack such an overview
**Possible Solution:** Create an overview based on @victoria-bondarchuk Research paper repo: https://github.com/victoria-bondarchuk/List-of-Academic-Research-on-Usability-in-FOSS

**Comment by jdittrich** [comment] 2017-03-17 14:19
related:
#69 – cross project communication

**Comment by bnvk** [comment] 2017-03-17 16:08
@jdittrich can you elaborate on what sort of overview you are ideally envisioning?

**Comment by jdittrich** [comment] 2017-03-17 16:29
Some notes: 
* There are incentives to introduce new features to open source software. Basically, there is few punishment for adding some functionality and probably quite some incentives to do so. (Usability in open source software development: Opinions and practice, Andreasen)
* There are no incentives of removing features, on the contrary
 * Power users will be annoyed (someone will have liked the feature) 
 * You will get rid of functionality someone else programmed in their free time, they won’t be happy 
 * Decision making will be based on consensus (Usability in open source software development: Opinions and practice, Andreasen); there are few usability experts, many non-experts and many opinions about not removing or substantially changing a feature.
* Creating code is seen as good/doing something, discussions, alignment etc. is seen as not doing something/not helpful
* Developers are not typical end users (The Usability of Open Source Software, Nicols, Twidale)

**Comment by jdittrich** [comment] 2017-03-18 12:22
@bnvk: Ideally something like an academic review (state-of-the-research) paper, naturally less academic, possibly including personal comments.

**Comment by belenbarrospena** [comment] 2017-03-20 09:43
I am planning to take some time off in May to write a PhD proposal on user-centred design in FOSS. As part of that, I will need to write a literature review, and I'll be happy to share it once written. 

You will need to wait for a few weeks though :)

**Comment by ninavizz** [comment] 2017-05-02 22:13
Academia, over-dependence on research, and whitepapers, imho, are contributing more noise than signal, to most of the problem. Simply: Design is a process that has users at the center, and isn't about colors, graphics, or logos. Tools such as GitHub work great for distributed dev teams, but much of what makes UX successful in products, is team culture & processes—with all project priorities pointing to identified user needs. 

What would be a far more valuable artifact would be a playbook, guiding teams and designers in how to work together, most effectively. Provide both with options, and influence empathy for one another's goals—that in the end, should all point to serving users.

Also, an observed general tendency in FOSS, is for developers to play the role that for-profit sector calls Product Mangement—ideating features, and just kinda adding them in a roughed-out form... later expecting a designer can smooth-out rough edges. That's not at all a user-centric approach, and for many reasons is problematic.

**Comment by ninavizz** [comment] 2017-05-02 22:54
This is a great example of a playbook kinda thing, created by 18F—the US gov's super kickass new(ish) digital services innovation group. It's for designers, by designers—and for designers in government agencies. Super simple, mostly visual, clearly demonstrative #dontmakemethink 

https://methods.18f.gov/

**Comment by grahamperrin** [comment] 2017-05-03 12:45
[The User Organisation: Structure and Governance in an Open Source Project](http://eprints.brighton.ac.uk/15449/) (Jose Christian, 2015) – PhD thesis.

Abstract: 

> User communities are a valuable source of innovation, where user-specific ideas and prototypes are developed and shared freely. Firms have begun to acknowledge the extent of their value at each stage of the innovation process, often resulting in commercially successful products. The current understanding of user communities, however, relies heavily on the study of software developers working on established open source projects. In recent years, with the emergence of web-based information and communication technology, open source projects and hacker communities have become much more complex, supporting a wider range of contributions from a diverse group of actors. While these technological advances have led to changes in the collaborative innovation, they have not been reflected in the user innovation literature.
> 
> Using the CyanogenMod project as a case study, this study explores how a user community manages multiple forms of contributions for the creation of multiple products and services. This study finds that the multiple forms of contributions create a number of communities of practice within the project, each with its own governance mechanism and leadership structure. In addition, the findings show that the activities of the different communities within the project are managed centrally by a separate leadership team who are responsible for setting and implementing long-term plans for the direction of the project as a whole. In light of these findings, this study proposes that the governance and social structures observed in the CyanogenMod project resemble a User Organisation rather than a user community, where the control over the stages of innovation can give users control over the direction and outcomes of the project.

(Jose and I work for the same research centre.)

**Comment by belenbarrospena** [comment] 2017-05-04 10:50
@ninavizz I agree with pretty much everything you say, including the idea of creating a repository of methods that have worked for us in the context of FOSS projects. 

However, I have to take issue with your statement about academic research contributing "more noise than signal". We stand in the shoulders of giants: in our day to day jobs we borrow heavily from multiple academic disciplines, and many of the designers who led the introduction of user-centered design in industry settings were academics themselves, or in some way involved with academia. I think we should be appreciative of their work, even if some of their output does not directly contribute to our applied design activities.

There is no harm in providing a summary of the relevant literature, which by all means will provide interesting context. 

@grahamperrin thanks for sharing that PhD. Sounds really interesting.

**Comment by bnvk** [comment] 2017-05-04 12:03
I think this conversation should be moved to the Discourse platform, no? I'm closing it, but re-open if I'm mistaken.

**Closed by bnvk** 2017-05-04 12:03 UTC

**Comment by grahamperrin** [comment] 2017-05-04 18:55
@jdittrich please: after the GitHub users in (at least) this topic are present at the forum, would you like this (one) issue to be migrated? Re: https://meta.discourse.org/t//46671/42 the migration service was unavailable for a few days, it's now operational. 

(I'll test first with an issue that I created.)

**Comment by ei8fdb** [comment] 2017-05-04 20:28
@grahamperrin If it is possible to migrate this discuss to discourse, then yes please do.

Everyone here, except (I think) @ninavizz is on discourse. @ninavizz please do join our discourse forum. Its for these kind of discussions.

It's dead easy and you can log in with your GH username - https://discourse.opensourcedesign.net/ and click signup.

**Comment by ninavizz** [comment] 2017-05-05 04:51
Re: Discourse @ei8fdb: Cool, got it—thank you. Had not previously seen that, despite poking around to see how to participate. 

On my prior comment: Absolutely, everything we do today was heavily informed by academia, and going forward academia will continue to inform what we do. No disrespect was at all intended to academic contributors, and I apologize for doing a poor job reflecting that in how I chose my words. Really, truly @belenbarrospena @grahamperrin. @jdittrich cited (in the comment above mine) that ideally a paper could be an output—and my objection was to the output suggestion, not the research endeavor/findings themselves. Re-reading the OG "Issue," I also realize that @jdittrich wrote it for existing FOSS contributors—not prospective ones.  

My point was in reference to existing **outputs** of academic work currently available, and outputs being prepared and published as complete white-paper studies, today. Traditional academic outputs are regrettably too far out of reach for mid-career designers—and many of us do want to get involved in FOSS, after student loans get paid off and we're hungry for new challenges.  

Most FOSS contributions are done on the side of day-job stuff... and the _service experience_ that's being created for UX designers wanting to contribute, needs to be considered as an equally high priority, parallel to new findings from additional research. I realize an obvious thought, is "Well you people should pay attention to academic journals, then!." We don't, though—and isn't the _raison d'erte_ of our profession, to put information where users will find it? In this instance, designers yet to be engaged in FOSS are users I'm not seeing considered—and given the volume of unusable FOSS products in need of more UX love, that's imho urgent. White papers as a published format, was what I cited my signal/noise disparagement with regards to—not the research itself. I also don't fault the academics or researchers for that, as whitepapers are research-credible formats for a reason. There's others of us in the pipeline of access, who need to step-up.

@grahamperrin The service experience your thesis can offer working professional designers (not researchers—_big_ difference in audience!) is the signal/noise frustration point I made a fumbly jab at speaking to. I'm delighted to see you're doing the work of a PhD Thesis on the topic (actually, more than delighted!)—I'm just feeling rather desperate, to see new works made more accessible to those of us not in academia, and many years removed from our own past academic endeavors. Too many have the interest, but refuse to bother because FOSS is too-opaque of a walled-garden universe to outsiders both long removed from academia, and many-years deep into corporate cultured careers. Users pay the ultimate price for too few UX folks being involved in FOSS, and as grateful as I am for all the meaty research, I want to see it put to work.

**Comment by grahamperrin** [comment] 2017-05-05 05:36
> … doing the work of a PhD Thesis …

It's not my work, but thanks `:-)` … three days ago I had a chat with the author about additional things that were learnt through the research. I might see him again next Tuesday (monthly meetings of the Centre). 

----

If you'd like to know more about my interests and experience, revisit https://discourse.opensourcedesign.net/t/-/41/22 in the **"say hi"** topic … maybe a few weeks from now. I'm not rushing to share information in that post because for me, whilst the forum takes shape, "it's nice to learn about other people" – more through their responses, across various channels, than through that topic alone. 

For now there's my basic profile (the avatar and so on), but please note that what's linked from the profile card is not representative of my interests in open source and in design.

**Comment by grahamperrin** [comment] 2017-05-12 18:17
> … migrate this discuss to discourse, …

Over to you, @jdittrich – or any other administrator. At your leisure. Thanks.

**Comment by jdittrich** [comment] 2017-05-12 18:51
I did recreate the topic and some answers on discourse: https://discourse.opensourcedesign.net/t/overview-of-problems-chances-and-practices-of-integrating-ux-and-open-source-software-development-ideally-based-on-research/150/2
