### ISSUE TITLE
Automatically let people join OSD

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/organization#50] opened 2017-02-14 19:12 UTC
@m1guelpf mentioned this platform: https://orgmanager.miguelpiedrafita.com/ 

Can we use this for automatically letting people join OSD rather than us always having to invite them?

**Comment by m1guelpf** [comment] 2017-02-14 19:38
@simonv3 It's very easy to setup.
You can use the hosted version at (https://orgmanager.miguelpiedrafita.com) or host it yourself (https://github.com/m1guelpf/orgmanager).

**Comment by simonv3** [comment] 2017-02-14 21:49
Do you mind setting it up for OSD so we can try it out?

**Comment by m1guelpf** [comment] 2017-02-15 18:08
@simonv3 The hosted one or the selfhosted one?

**Comment by simonv3** [comment] 2017-02-15 22:54
@m1guelpf either! If you think the hosted one is enough then that would be great :)

**Comment by m1guelpf** [comment] 2017-02-16 17:58
@simonv3 The hosted one should work...
You just need to register on the hosted version with a Github account that has admin permissions to this org. If you need more help, you can either ask here or use the chat provided in the website.

**Comment by simonv3** [comment] 2017-02-16 18:15
Hmm, does the application automatically create links for all orgs that I'm an admin for? That's not desirable on my end.

**Comment by m1guelpf** [comment] 2017-02-16 18:27
@simonv3 You should give access to the organizations you want to generate links for. The sync function syncs the ORG name and description from Github. To enable password-protection, just enter any password in the password field and press submit. To remove it, remove the password from the password field and press submit.

**Comment by simonv3** [comment] 2017-02-16 18:47
I don't see a way to specifically only give access to some organizations. I'm not sure GitHub allows for that - it defaults to the organization's permissions in relation to the user.

**Comment by m1guelpf** [comment] 2017-02-16 18:49
@simonv3 You can check, give and remove permissions and organizations to orgmanager at this link:
https://github.com/settings/connections/applications/10b01d866046f040c9f1

**Comment by simonv3** [comment] 2017-02-16 20:22
@m1guelpf can we take this [to a chat](https://webchat.freenode.net/?channels=opensourcedesign). I don't think I can edit anything on that page specifically. It automatically checks all the organizations that I'm a member of, and I don't think there's a way to unselect them unless I'm missing something.

This might be a limitation on GitHub's authentication system, but in the mean time I still don't want to have organization join links available for orgs that I don't want people to have access to if they stumble across a URL.

**Comment by m1guelpf** [comment] 2017-02-16 21:09
@simonv3 Could you send me an screenshot of the page where you can't cancel your org permissions.
Also, could you open an issue for that password glitches?
I am not able to chat over irc, but you can email me or use the chat of the website (that goes to my mail anyway :smile:).

**Comment by simonv3** [comment] 2017-02-16 21:32
Screenshot: 

![screenshot 2017-02-16 12 20 35](https://cloud.githubusercontent.com/assets/485583/23041793/b23a2f42-f442-11e6-9119-c4eb050e3677.png)

I've opened some other issues as well.

**Comment by simonv3** [comment] 2017-02-17 22:24
Awesome, thanks to the quick response time by @m1guelpf this might be an option: 

https://orgmanager.miguelpiedrafita.com/join/4183553

**Comment by m1guelpf** [comment] 2017-02-18 07:50
@simonv3 Just checked to see if this worked, and it gives an error.
Seems like your github token is invalid. Could you revoke the orgmanager permission and try to login again?
(You can revoke it in the link i sent you before)
Thank you!

**Comment by simonv3** [comment] 2017-02-19 23:52
@m1guelpf went ahead and did that.

looks like it's the same link, but try again? https://orgmanager.miguelpiedrafita.com/join/4183553

**Comment by jancborchardt** [comment] 2017-02-21 18:01
Awesome! :) Then we can finally add a link for people to add themselves.

@m1guelpf is there also an easy way to have the visibility of people set to »Public« by default? The current standard of »Private« is a bit annoying because we have to ask everyone.

**Comment by m1guelpf** [comment] 2017-02-21 19:22
@jancborchardt There isn't an API endpoint to do that for security reasons, and also it would not be possible as the user needs to accept the invitation before we can modify status via the API. Sorry 😞

**Comment by m1guelpf** [comment] 2017-02-21 19:23
Also, if you have some ideas/things that orgmanager could do, feel free to open an issue in the repo, as after releasing v2.0 I've run out of ideas 😄

**Comment by jancborchardt** [comment] 2017-02-22 10:57
@m1guelpf awesome! I opened a bunch of issues :)

**Comment by m1guelpf** [comment] 2017-02-22 12:26
@jancborchardt Thank you!

**Comment by m1guelpf** [comment] 2017-03-09 20:31
@simonv3 @jancborchardt I've noticed you used to add your users to an organization team (https://github.com/orgs/opensourcedesign/teams/people). I've just deployed a new fuction that allows you to select a group users will go into. You can access it in the organization settings in OrgManager.

**Comment by simonv3** [comment] 2017-03-09 21:50
Oh great, knew we were forgetting something.

**Comment by simonv3** [comment] 2017-03-09 21:52
And done. That was the last piece of the puzzle. Thanks so much for being so responsive @m1guelpf, this is awesome.

**Comment by m1guelpf** [comment] 2017-04-14 11:00
@simonv3 @jancborchardt I've recieved multiple messages of users that can't join OSD using OrgManager. I've debugged and the cause seems to be a GitHub authorization error: "You must be an organization owner or team maintainer to add a team membership." It seems that the person who registered OSD into OrgManager's privileges were revoked and that person no longer has admin access to the People team. Could you investigate this?

**Comment by simonv3** [comment] 2017-04-14 15:01
Wasn't I that person?

**Comment by m1guelpf** [comment] 2017-04-14 18:20
@simonv3 Reading TVE los, it seems like GitHub throwed an unauthorized issue with "Must have admin rights to Repository" when you tried to sync teams...

**Comment by simonv3** [comment] 2017-04-14 18:28
@m1guelpf I have admin rights though. Are you sure it's requesting the rights in my name?

**Comment by m1guelpf** [comment] 2017-04-14 18:36
@simonv3 I've just tried to retry the requests manually using hurl.it, and here is the response:

![screenshot_2017-04-14-20-34-58](https://cloud.githubusercontent.com/assets/23558090/25052407/f90d25c8-2151-11e7-9418-809434b22798.png)

**Comment by m1guelpf** [comment] 2017-04-14 18:38
@simonv3 I've deleted the GitHub token fron the database, could you please logout and login again?

**Comment by simonv3** [comment] 2017-04-14 18:46
@m1guelpf I did and no luck. Maybe we should chat on IRC?

**Comment by m1guelpf** [comment] 2017-04-14 18:57
@simonv3 Maybe we could chat in the OrgManager gitter: https://gitter.im/orgmanager

**Comment by m1guelpf** [comment] 2017-04-14 19:18
@simonv3 Also, could you try to revoke the OrgManager oAuth permission and login again (https://github.com/settings/connections/applications/10b01d866046f040c9f1) or, if that doesn't work, maybe another admin can sign up and I can manually change the user ID in the database... It seems to be working for the rest of organizations...

**Comment by m1guelpf** [comment] 2017-04-14 19:27
Seems like Gitub had revoked somehow the permissions for OrgManager... fixed now. I will open a ticket with GitHub later to know more... Thank you @simonv3 !

**Comment by simonv3** [comment] 2017-04-14 19:28
Thank _you_ @m1guelpf!

**Closed by m1guelpf** 2017-04-14 19:27 UTC

**Comment by m1guelpf** [comment] 2017-04-24 20:10
@simonv3 @jancborchardt Just wanted to drop that https://github.com/orgmanager/orgmanager/issues/48 was just closed, and now you can set a custom message that will be displayed to users when they're invited. It's a good place to ask people to accept your invite and change their membership to public!

**Comment by jancborchardt** [comment] 2017-04-29 17:25
@m1guelpf awesome! :) @simonv3 can you maybe adjust that to ask people to accept and set their visibility to public?

**Comment by simonv3** [comment] 2017-05-03 15:07
I already did!
