### ISSUE TITLE
Open Source Design needs a new logo

### ISSUE THREAD

**Issue by belenbarrospena** [opensourcedesign/organization#68] opened 2017-03-08 10:37 UTC
[As agreed in our monthly call on March 7th](https://github.com/opensourcedesign/events/issues/49#issuecomment-283646202), I am opening this issue to create a new logo for Open Source Design.

As per [this comment](https://github.com/opensourcedesign/events/issues/43#issuecomment-283807989), our current logo is violating the Open Source Initiative trademark. 

Luckily, there are a bunch of excellent graphic designers amongst us, so it shouldn't be too hard for us to come up with a brand new logo. 

Let the graphic design talent burst forth! ;)

**Comment by gillisig** [comment] 2017-03-08 10:46
![osd-triangle](https://cloud.githubusercontent.com/assets/5390864/23700849/2fa73d04-03ec-11e7-8a93-7e8e41bee12b.png)

I posted this in our IRC channel a couple of days ago. It was inspired by @elioqoshi summit logo. I thought why not have the main logo as one triangle and summit as two.

I would also like to add that I would love it if we would pick a brand color as well. I find the black and white colorscheme rather dull for a group of designers.

**Comment by jancborchardt** [comment] 2017-03-08 11:58
We currently have a circle, the next most basic form is a square:
![opensourcedesign-logo-square](https://cloud.githubusercontent.com/assets/925062/23703062/57c3338a-03fe-11e7-9a52-8e14dc908e73.png)

The issue I see with the triangle is that it’s like an **A** letterform. And there is no A anywhere in »Open Source Design«. That’s why the **O** circle logo is so good for »Open Source« of course. So I thought about putting it in a **D** letterform:

![opensourcedesign-logo-d](https://cloud.githubusercontent.com/assets/925062/23703154/c4e71558-03fe-11e7-8b05-7271f3b5bfba.png)


Mirrored the negative space form so maybe the D is more visible:

![opensourcedesign-logo-d-mirrored](https://cloud.githubusercontent.com/assets/925062/23703155/c4ea5af6-03fe-11e7-8bfd-dea24c52517c.png)

**Comment by aoloe** [comment] 2017-03-08 11:59
and a F for free?
not that easy, but...

the pencil is already there to signify the design part...

**Comment by bnvk** [comment] 2017-03-08 12:37
Nice. I don't have access to my design computer at the moment (otherwise I'd
whip up a variation), but one to consider for our logo- do need a standalone
logo that goes alongside "Open Source Design" or should we perhaps try to
fashion the logo out of our initials "OSD" ?

Perhaps appending an "OS" + "D" with brush made by @jancborchardt could
work?

**Comment by linchocolatte** [comment] 2017-03-08 12:58
If you guys are interested, I actually did a brand identity design for my
FYP based on OSD. I can post it here and see if we could work using that as
well? (:

**Comment by jancborchardt** [comment] 2017-03-08 13:06
@bnvk I’m highly against abbreviations because they are not easily understandable. Also, »OSD« already stands for things like »On-screen display« and »Open Source Definition« … ;) That’s why I prefer us using the full »Open Source Design« at all times and avoid »OSD« because it’s insider jargon.

@linchocolatte sure, go ahead! :)

**Comment by linchocolatte** [comment] 2017-03-08 13:09
Cool! I guess you can view it here for now:
https://www.behance.net/gallery/45265017/Open-Source-Design-Branding-Identity

My approach is kind of a revamp of the identity, but it could be altered
according to what feels right or what feels wrong (:

**Comment by bnvk** [comment] 2017-03-08 13:30
@lintchocolate these are really cool, thanks for sharing them and welcome to 
OSD :) 

For max collaborations: I think it would be great if we could collect all
the raw source files of designs and logos for OSD from our previous logo and
now this new one into a repo. Perhaps here? Or in `logos` ?

How does that sound to others?

**Comment by jancborchardt** [comment] 2017-03-08 13:47
@linchocolatte wow that looks awesome! Especially because it’s a whole identity that we could also revamp the site with. It’s very welcoming and colorful, also speaking to more general designers not knowledgeable yet about open source.

What do you think @belenbarrospena @gillisig @simonv3 @victoria-bondarchuk @evalica @ei8fdb @jdittrich @Incabell @eppfel @andreasn @elioqoshi @Xaviju? Any other proposals?

@bnvk good call! I added a link to the source files in my comment for remixing.

**Comment by L-A** [comment] 2017-03-08 14:15
Really loving @linchocolatte's suggestion. It's easy to read, with good personality. It might need some work on the word-less version, but the foundation there is great.

Quick note on the above triangle version, just to be good neighbours: It's reminiscent of Zeit's logo – and they happen to be very active in the OSS community.

https://zeit.co/

**Comment by linchocolatte** [comment] 2017-03-08 14:32
@jancborchardt yeah since it was part of my project, I did over-experimented with the photography HAHA. But yes we could replace them with images like you said. 

If you would like, I could upload the source file somewhere. Then we could figure out how to improve it and make it much closer to what the open source design community really is about.

**Comment by jdittrich** [comment] 2017-03-08 18:45
@jancborchardt: I really like @linchocolatte design, too. Thanks for creating!
@jancborchardt: pro meetup/mockup photos. I got some libre [paper+hands-Photos here](https://www.flickr.com/photos/31068346@N05/)
@bnvk: I second this. Sources, please :-)

**Comment by evalica** [comment] 2017-03-09 07:03
FTR @elioqoshi proposed some logos over IRC (can't find the archives so please resubmit them here). 

Also (in order to not be lost) he made some proposals for the Summit: 
- 1 https://github.com/opensourcedesign/organization/issues/57#issuecomment-283674358
- 2 https://github.com/opensourcedesign/organization/issues/57#issuecomment-283890415
- 3 https://github.com/opensourcedesign/organization/issues/57#issuecomment-283946644

**Comment by elioqoshi** [comment] 2017-03-09 08:53
Love @linchocolatte direction as well! We gotta agree on a logo mark first, but could definitely go in that direction for the whole brand. I agree that we need some colors at some point.

**Comment by andreasn** [comment] 2017-03-09 12:06
I like @linchocolatte's design with regards to it's straight-forwardness with "open-source+design" and simple use of energizing, intense colors. (I don't fully understand the candy connection, but I'll avoid diving too much into the whole brand identity and focus on the logo for now)

The 45 degree diagonal the words create could also be repeated in patterns etc.

I also like the idea to move away from the brush, since the brush can give the idea that it's all only about painting and making things look good, and not on the deeper design process.

**Comment by Incabell** [comment] 2017-03-10 12:33
I like @linchocolatte 's design a lot. It does remind me a lot of this [Grassroots-Thinktank](http://polis180.org/) (who's design I also like very much).
and +1 to what @andreasn said about the brush. 

Do we still need a logo mark as @elioqoshi suggested if we go in the direction of @linchocolatte 's design?

No matter what we go with, I would like to have the files available in SVG or whatever other format is usable by open source software. Just cause I saw that @linchocolatte offered to upload the files somewhere but your portfolio sais you worked with Illustrator and Photoshop so I just wanna make sure we will have files that anyone can remix and use.

**Comment by Xaviju** [comment] 2017-03-10 13:19
I agree on moving from the brush. 🖌 
I love the colorful identity by @linchocolatte, specially the use of images. Very nice!
I'm not so sure about the core design elements. (`-` and `+`) I think it might have multiple interpretations. Could we try removing the `-` symbol? Something like `Open Source + design`.

Thanks for the design @linchocolatte its an amazing starting point.

**Comment by linchocolatte** [comment] 2017-03-10 13:40
@charlie yeah I should be able to save the files in svg! Just need to
direct me where to upload it (:
@xaviju Feel free to alter it according to what feels right for you,
afterall it's a design process! haha.

**Comment by Xaviju** [comment] 2017-03-10 13:48
@linchocolatte thanks! I'd like to avoid the [_Design by committee_](https://en.wikipedia.org/wiki/Design_by_committee) and I really like your work direction so think about my suggestion and do what you think is better. ;)
To share the file, I usually upload the file to a service (like owncloud, nextcloud or similar) and share the link here.

**Comment by linchocolatte** [comment] 2017-03-10 13:50
@xaviju Cool! I'll probably have some variations and then package the files
asap when I have the time! :D

**Comment by bnvk** [comment] 2017-03-10 14:59
> I agree on moving from the brush.

This would make me sad.

Brushes are a very old and widely recognized visual representation of art and 
creativity. We (OSD) created & chose it via consensus.

I'm very happy with one of @elioqoshi variations and would allow us to move 
onto other design tasks and improvements than investing more time into 
something we've already worked on and had a pleasing result.

But hey, designers gonna design :P

**Comment by simonv3** [comment] 2017-03-10 16:40
I like the brush too, but I don't know if that's as a historical artifact of our organization. Like I said in the IRC - I would love to see something with the brush worked into the design by @linchocolatte (which is awesome). I don't see the -s mentioned - more like squares?

The fact that I had no idea @linchocolatte made these intrigues me - is there more stuff people are making around OSD that I'm just not aware of? How do we keep track of things like that?

**Comment by ryangorley** [comment] 2017-03-10 19:25
To me what is strong about the Open Source Initiative logo is that it reads like a key hole, which is kind of a nice way of thinking about open source, as something that unlocks things. The OSD logo, whether deliberate or not, reads to me like a play on that symbolism, but with a clear design slant. Inscribed in some other shape, the brush loses that connection and the whole mark becomes generic. Perhaps a case can be made that enough people associate the brush with OSD that the prior meaning is no longer relevant. I'm a newcomer here, so I'm not in a place to dispute such an argument.

I agree that @linchocolatte has created some beautiful work (kudos, btw). The plus symbolism relating to collaboration is cleaver, and something I hadn't thought of. Other than looking good it doesn't seem to have a symbolic relationship to design specifically. It could perhaps acquire that by shifting to a color scheme associated with design (i.e. CMYK).

Is there a way to marry the current brush symbol with something related to code, such as perhaps ones-and-zeros, computer peripherals, brackets/semi-colins, etc.? Energy drinks? ;) If we cannot retain the "open" meaning of the mark, perhaps we can more strongly associate it with the people we're serving.

**Comment by jancborchardt** [comment] 2017-03-10 21:54
Regardless whether we use the brush or @linchocolatte’s proposal or anything else – I do like the holistic approach of branding that @linchocolatte did.

We do not only need a logo, but an identity. It would also help our website to be more friendly. :)

**Comment by elioqoshi** [comment] 2017-03-11 09:34
I actually am surprised quite a few people want to move away from the brush when it was decided via consensus in the first place. It took us a very long time to get to that consensus and I don't think we should spend our time to repeat that. 

I personally would be happy to move on with a classic OSD logo, tweaked to cater to OSI's requests, implemented in a branding direction @linchocolatte suggested.

That would be the good of both worlds, don't you think?

**Comment by bnvk** [comment] 2017-03-11 12:49
> whether we use the brush or @linchocolatte’s proposal or anything else

I see this as an *and* not an *or* which would maximize progress / minimise
work.

**Comment by elioqoshi** [comment] 2017-03-11 14:42
What @bnvk says. The design language / brand identity and the actual logo we will use aren't necessarily overlapping.

**Comment by linchocolatte** [comment] 2017-03-11 14:59
During my design process, I have actually implemented the existing OSD logo
(as it is alrd associated eith OSD itself) and it looks fine! Gimme a few
days, as I'm currently outstation, and I'll be uploading the link here (:

**Comment by jancborchardt** [comment] 2017-03-12 00:02
@linchocolatte that sounds very cool! :) Looking forward

**Comment by grahamperrin** [comment] 2017-04-05 20:21
Re: #79 the Discourse instance will benefit from two variants of a logo: 

1. wide rectangular, to appear initially at top left
2. square, to appear when scrolling down. 

After URLs for the two become known, I'll add them to the settings in Discourse.

**Comment by studiospring** [comment] 2017-04-06 05:31
To throw another spanner in the works, if the name "Open Source Design" is part of the logo/branding, I would also like some discussion about the name of the organisation. The problem with "Open Source Design" as the name of the organisation is that it becomes difficult to tell whether I am talking about the organisation or the concept.

Not so obviously, I can use lowercase for the concept and uppercase for the organisation, but when it is abbreviated or spoken, they become the same. We have FLOSS, FOSS, OSS and now OSD, but only OSD refers to both an organisation and a concept. Some alternatives include:

- Open Source Design Network (OSDN), which works well with the current .net domain and is to me a more accurate description of what we are.
- Open Source Design Organisation (OSDO), which rolls off the tongue better and sounds more "can-do".

Have I rocked the boat too much?

**Comment by AlexxNica** [comment] 2017-04-06 12:52
@studiospring Excellent idea! Couldn't agree more. I'm for **Open Source Design Network (OSDN)**.

**Comment by linchocolatte** [comment] 2017-04-06 13:22
@jancborchardt this is the variation of the logo I was talking about. Sorry it took so long!

![logo variation](https://cloud.githubusercontent.com/assets/18112033/24756057/04f057a0-1b0f-11e7-9f6e-8fd2328e4bfc.png) (This is the variation done using the symbol of OSD whcih we all know)
![logo variation 1](https://cloud.githubusercontent.com/assets/18112033/24756059/059a44ea-1b0f-11e7-8990-f36f29365963.png) (This is the one I chose for my FA)

**Comment by elioqoshi** [comment] 2017-04-06 17:07
Thanks @linchocolatte ! We might want to have a go at the current logo / the squared version, would you be able to do that? Maybe we can try some different colors as you did

![test-01](https://cloud.githubusercontent.com/assets/5436686/23742940/1fc18bf6-04af-11e7-9a00-a8c4fc78f78f.jpg)

**Comment by simonv3** [comment] 2017-04-06 17:52
@studiospring in fear of your comment getting lost in this thread, can you create a new issue? Or maybe wait until we're on Discourse? (I imagine we'll have to migrate some threads).

**Comment by studiospring** [comment] 2017-04-06 23:58
@simonv3 if Discourse is up in the next week or so, I'll create a thread there (no pressure, @grahamperrin ;-)). Otherwise, I'll create another issue here.

**Comment by eppfel** [comment] 2017-04-07 10:17
I'm no fan of the brush, as I feel a lot of my work as a designer is teaching people, that it is not only about putting colors on a sheet (pixels on a screen), but I understand your concerns.

To move away from the OSI, I don't think we have to get rid of the circle, because it is too generic to be claim by OSI. The problem is that the way we cut the circle, is clearly the same, as in the OSI logo.

I played a bit to show my idea. I think the "avatar" is nice because it represents OSD as a **collective**. We are not based on a few businesses collaborating, but we are a bunch of designers.

What I like about all three: The incorporate the OSD: The circle is for **O**pen, the brush head has an **S**-curve and the beginning of the handle is for **D**esign.
![avatar](https://cloud.githubusercontent.com/assets/1899308/24795959/7eb087c8-1b8b-11e7-87f6-fba2ea0dc58d.png)
![down](https://cloud.githubusercontent.com/assets/1899308/24795960/7eb331e4-1b8b-11e7-95e9-dad977c32503.png)
![up](https://cloud.githubusercontent.com/assets/1899308/24795961/7eb68b5a-1b8b-11e7-8a7a-2547c4dc97d2.png)

They all need some refinement and look to generic for now, but as a start... what do you think?

**Comment by belenbarrospena** [comment] 2017-04-07 10:41
@eppfel I am really impressed by your proposal. Some serious thinking showing there. I particularly like versions 2 and 3, and how playful we could get by using different angles in different places. 

Version 2 is particularly pleasing for some reason. It might be because it reflects the natural position of a brush or pencil.

I love it :)

**Comment by grahamperrin** [comment] 2017-04-07 10:49
I see the claw of a crab: 

![down](https://cloud.githubusercontent.com/assets/1899308/24795960/7eb331e4-1b8b-11e7-95e9-dad977c32503.png)

Keep the ideas coming, folks. All very pleasantly thought-provoking!

**Comment by belenbarrospena** [comment] 2017-04-07 10:53
ROFL. It took me a while, but true!

**Comment by Espina2** [comment] 2017-04-07 18:48
I think that it should be more focus on the word open, right now the simbol doesn't feel like is something that belong to the open source.

**Comment by simonv3** [comment] 2017-04-07 20:19
We've kind of been through this before and either a bunch of people put forward their designs and we vote on them or we assign someone to focus on this and suggest a design. People can give feedback on those designs, but I'm not sure it's productive to have everyone pitching in ideas without end. 

We definitely need to set a deadline, whichever route we decide to go.

**Comment by elioqoshi** [comment] 2017-04-08 21:14
>What I like about all three: They incorporate the OSD: The circle is for Open, the brush head has an S-curve and the beginning of the handle is for Design.

I think you are reading a bit too much into it. I'd never be able to see that, and don't really now that you said it.

I think we should stay true to our logo as we have been bikeshedding about it enough. Let's just make it compatible with OSI and get over with it.

**Comment by grahamperrin** [comment] 2017-04-09 03:59
From what I have seen (not a comprehensive view), across multiple issues, I vote for this option: 

![logo-hexagon-2017-03-09](https://cloud.githubusercontent.com/assets/192271/24834547/058f90a8-1ce1-11e7-96a9-37b8f01f1ebd.jpg)

I'll make a separate post to show how that option _might_ appear in the forum …

**Comment by studiospring** [comment] 2017-04-09 04:37
Before this issue gets shut down, I'd like to throw my 2 cents in there. It is worth considering the other logos of the open source family and keep ours consistent with that family. It is also important not to cause confusion with other logos (like the Open Source Robotics Foundation).
![oshardware](https://cloud.githubusercontent.com/assets/4901306/24834751/83ac9756-1d31-11e7-8750-824f594272ab.png)
![osrf](https://cloud.githubusercontent.com/assets/4901306/24834760/ae672c5e-1d31-11e7-8b8e-cdc219a04cdc.png)

![jordan_open_source_association_logo](https://cloud.githubusercontent.com/assets/4901306/24834730/13a0ed22-1d31-11e7-9787-3899ba6f0044.jpg)
![index](https://cloud.githubusercontent.com/assets/4901306/24834731/1517dc9c-1d31-11e7-9b5b-731f4f24c297.png)
![index](https://cloud.githubusercontent.com/assets/4901306/24834732/1a6aeb08-1d31-11e7-8ae9-b457edff7f09.jpg)



You will notice that they all keep the key hole and thus keep the connection with the original OSI logo quite clear. Personally, I think the OSD logo is the least clear.

I would suggest that the vision and purpose of OSD be made clearer before thinking about logos. I think OSD goals etc could do with a rewrite. Once that is clear and a proper brief for the logo (with deadline) is set out, logo design should be a lot easier.

**Comment by elioqoshi** [comment] 2017-04-09 18:07
@studiospring pretty sure most of the logos you mentioned are against OSI Trademarks. I think OS Hardware also changed it.

Again, we are mostly doing this change to abide with OSI's ask to change the logo, rather than finding our "true self".

**Comment by ei8fdb** [comment] 2017-04-09 20:36
I get busy at work for a month and discussions explode! I can't keep up with all the discussions!

I really like the identity @linchocolatte has created. I think it lends itself to more than just a logo. I also like the way she has given some

Yes it is different from the Open Source Initiative inspired logo but...look where that got us. ;)

@linchocolatte I like the [first riff you did combining the brush](https://github.com/opensourcedesign/organization/issues/68#issuecomment-292172773) (above). I wonder if that is still too similar to the OSI logo?

Whatever the decision I totally agree with @simonv3,

> We definitely need to set a deadline, whichever route we decide to go.

The need to come up with a compatible logo was important, I think still is. I'd presume, until we have a new one, we can't create any new materials.

How should we move this on? I propose we run a logo submission again, in order to make some progress. 

Otherwise we'll be discussing this again 1 month before the next FOSS conference. ;)

**Comment by studiospring** [comment] 2017-04-10 01:08
Thanks, @elioqoshi. Didn't know that. Is the OSI's request to us publicly or privately available? I would be interested to understand their concerns. Having an affiliation reflected in the logo seems like a positive to me.

**Comment by grahamperrin** [comment] 2017-04-10 01:50
AFAICT the first post from _massonpj_ to an https://github.com/opensourcedesign issue was https://github.com/opensourcedesign/events/issues/43#issuecomment-268285534 (2016-12-20).

**Comment by elioqoshi** [comment] 2017-04-10 13:51
@studiospring Yep, it was public as @grahamperrin mentioned. That's priority for now.

We are way too much bikeshedding here I fear. If we go on like this we won't be resolving this matter any time soon.

**Comment by jdittrich** [comment] 2017-04-10 14:47
So, what about the square or the D that @jancborchardt proposed way up? Seems to be the quickest fix.

**Comment by grahamperrin** [comment] 2017-04-10 15:05
Both versions of the **D** appear to be at risk of toppling over, to the right, and then rocking on the curve of the letter. 

----

Overwhelmingly, unavoidably: the logo that I most often associate with Open Source Design is the GitHub logo. So I'm not averse to future bike sheds :-) leading to a _great_ logo (or combination of logos) but for now, I'll settle for any logo that is _satisfactory_.

**Comment by simonv3** [comment] 2017-04-11 00:28
@massonpj does the OSI mind if we start up a new platform of discussion (we'll use it discussing the logo redesign process) and use the current Open Source Design logo (the circle with the paintbrush) in the header of that platform for our own brand consistency?

**Comment by massonpj** [comment] 2017-04-11 13:05
Hi @simonv3, unfortunately the OSI cannot give consent to use a logo we consider to be infringing on our own marks. In a response to @studiospring I discussed this a bit: https://github.com/opensourcedesign/events/issues/43#issuecomment-293251166

Of course, we rely on the good will of the community, and realize the whole OpenDesign community is engaging honestly, openly and transparently to remedy the conflict in marks in the best way that you can.

**Comment by elioqoshi** [comment] 2017-04-11 13:53
Can we please go ahead with the square OSD logo proposal to solve this and if there is really a need to rebrand we can do so later? We have to solve the matter with OSI first before we talk about our identity.

**Comment by simonv3** [comment] 2017-04-11 15:14
@massonpj thanks for the very quick response!

@elioqoshi - I agree. I think we should use the square logo for now, switch all of our branding, and continue the conversation with the full knowledge that we're going to continue designing the logo and identity. Can you get us an svg of the logo?

# Vote

## Can we use the temporary square logo to solve the OSI logo while we figure out our brand and identity, so that OSD can move on from this one issue?

To vote, please do thumbs up or thumbs down on this post. As per the [by-laws](http://opensourcedesign.net/by-laws/) I'll stop counting in two weeks (April 25th). If you do do a thumbs down, please suggest an alternative in the comments.

**Comment by grahamperrin** [comment] 2017-04-11 19:04
I might change my vote in an hour or less but at the time of writing I prefer [the hexagon](https://github.com/opensourcedesign/organization/issues/68#issuecomment-292762390) (above, with an upvote from Eli Schiff). 

I'll experiment with the square at the forum, but please give me time.

**Comment by simonv3** [comment] 2017-04-11 22:04
@grahamperrin I understand this vote as not as much about which of the propositions you prefer but rather about using a placeholder so that we can move on from the OSI issue while we figure out our identity as a whole.

**Comment by grahamperrin** [comment] 2017-04-11 22:56
Understood, thanks. 

https://github.com/opensourcedesign/organization/issues/79#issuecomment-293421171 is the promised experiment with the square. 

> … suggest an alternative in the comments …

My suggestion for a placeholder is [the hexagon](https://github.com/opensourcedesign/organization/issues/68#issuecomment-292762390). 

I see a lack of harmony between the square and the circles. 

There's not _great_ harmony between a hexagon and circles, but I felt better about the hexagon whenever I saw it. 

I see the angles of the lines beneath the brush of the paintbrush as: 

- reasonably harmonious with the angles of the hexagon
- clashing with the upright sides of the square. 

More subtly – and I'm sorry that most people have not had an opportunity to _work with_ a site that uses the hexagon – with a desktop web browser, it somehow **felt** good to have the naturally angled arrow pointer cursing to and from an object with angled sides. Extracted from the screenshot at https://github.com/opensourcedesign/organization/issues/79#issuecomment-292762807: 

![69c09fc6-1ce2-11e7-9e54-5c223725b4ab](https://cloud.githubusercontent.com/assets/192271/24934259/65a6dd24-1f12-11e7-9982-7a5bac74c4fa.png)

**Comment by grahamperrin** [comment] 2017-04-12 10:58
Sorry, I only just found this edition (and from GitHub, I can't tell when the edition occurred compared to the original): 

> … Edited to elaborate: … 

If it helps towards a shared understanding: 

- I have "no objection" to temporary/interim use of either the hexagon or the square. 

(Please, have I understood things correctly?)

My downvote, which I have removed to avoid misunderstanding, was not an objection to the temporary/interim aspect.

**Comment by jancborchardt** [comment] 2017-04-12 11:06
The square logo source is at https://cloud.jancborchardt.net/s/opensourcedesignlogo as posted above:
![opensourcedesign-logo-square](https://cloud.githubusercontent.com/assets/925062/24954635/830e2db8-1f80-11e7-9cd8-acd178c70c60.png)
(opensourcedesign-logo-square.svg) cc @simonv3 

@massonpj thanks a lot for your patience. Logo redesigns take some time, especially in such a big community, of designers at that. ;) Hope the squaring out is a proper solution for now.

**Comment by grahamperrin** [comment] 2017-04-12 11:09
## Additional clarification

If my posts about the hexagon were misinterpreted as a proposal for _long-term/permanent_ use of the hexagon: sorry; that was not my intention. I did read, and continue to read, this issue 68 in the context of earlier/broader issues such as https://github.com/opensourcedesign/events/issues/43 where (unless I'm missing something) there are no oppositions to other suggestions that a _temporary/interim_ change of logo will be a mutually agreeable approach.

**Comment by jancborchardt** [comment] 2017-04-13 10:54
The forum at https://discourse.opensourcedesign.net now uses the square logo, and I also changed it to the square version at https://twitter.com/opensrcdesign and https://github.com/opensourcedesign

Will also clean up the logos in our website repository. :)

**Comment by elioqoshi** [comment] 2017-04-15 07:22
@jancborchardt I think the logo on the main page is way too big. Can we make it smaller? Also, the font used there is different (it should be Montserrat IIRC)

**Comment by jancborchardt** [comment] 2017-04-19 19:07
@elioqoshi you can also adjust it directly, that’s easier. :) And the font should be Open Sans, we use that everywhere. (At least so far.)

**Comment by elioqoshi** [comment] 2017-04-23 13:49
Well, no. The font was Montserrat for the Wordmark on the top bar. This is why I asked.

**Comment by jancborchardt** [comment] 2017-04-29 18:13
@elioqoshi ah right, the body text is Open Sans, logo is Montserrat.

**Comment by jancborchardt** [comment] 2017-09-05 18:04
I would say that our new square logo with Montserrat Bold is a pretty good current logo. It’s already a bit known by people so it would not be that wise to change it around. We mainly wanted to change it to fix the trademark conflict, and that we did.

I’d close this issue hence. :) If you feel differently, feel free to comment.

**Closed by jancborchardt** 2017-09-05 18:04 UTC
Labels: design, discussion
