### ISSUE TITLE
Open Source Design Summit attendance & actual session proposals

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/organization#95] opened 2017-08-01 17:33 UTC
Since we now approach more concrete planning for the Summit, we should start thinking about topics, workshops and sessions everyone wants to do. :)

# Meta:

- Start: Introductions session / Status for OSD community (at the beginning)
- Start: Unconference / Brainstorming about what we want to discuss at the Summit
- Lunch / Dinner planning (time)

# Workshops so far:

- @victoria-bondarchuk proposed to have a session about a manifesto for Open Source Design, shared knowledge about what we stand for and what we value (we should iterate on http://opensourcedesign.net/about/)
- @simonv3 will lead a session on figuring out what we want from our website, our job board, and how to build it and host it.
- Small status / planning session for FOSDEM **Looking for host**
- Our #brand. **Looking for host**
- Making OSD sustainable organization and membership wise. @simonv3 can host if no one else wants to.
- Growing OSD beyond its current membership, and engaging more of our members. @simonv3 can host if no one else wants to.
- Forming as an official organization. **Looking for host**

# Talks: 
- @dimitrieh mentioned it would be important to have a single source of truth of what we do – make it clear what we use Discours for, what Github issues, etc.
- @jdittrich: Talk/Discussion Proposal: UX debt and why it is a particular problem for open source projects. [Description](https://github.com/opensourcedesign/organization/issues/95#issuecomment-327244751)
- @tessgadwa would be interested in talking about structural and systemic issues affecting usability and FOSS. Wondering if a "best practices for UX in open source" might be better as a collaborative session for an unconference and/or workshop.
- @cameralibre would like to run a 1-2 hour version of an 'analog open source collaboration' workshop. See [Teaching Open Source collaboration to designers (without digital tools!)](https://discourse.opensourcedesign.net/t/teaching-open-source-collaboration-to-designers-without-digital-tools/289)
- @digitigrafo would like to do a small talk about "Redesign comment platform". I'm involved in this project http://www.scholio.net/ and I like to share the info that I collected about: which are the commons problems, what propose critical thinking, cases of study. thanks

- who else @jdittrich @evalica @bnvk @Incabell @elioqoshi @belenbarrospena @ei8fdb everyone! :)

Everyone please post **when you will attend** the summit and **which session/workshop/talk you want to contribute**! :) Also please RSVP at https://opencollective.com/opensourcedesign/events/opensourcedesign-summit

**Comment by jancborchardt** [comment] 2017-08-01 17:38
I will be there the whole time. :)  And I’d like to talk about how we can organize multiply ourselves:
- achieving a serious look for our website and a coherent system
- having showcases for well-designed open source projects & products ready to use, and for design tools & resources
- conferences we can talk at or organize design tracks at, design as well as open source ones
- getting more designers involved and post on our blog

**Comment by tessgadwa** [comment] 2017-08-01 17:39
@jancborchardt  Hi I'm in. Would love to talk about best practices for UX in open source, sharing case studies and specific examples.

**Comment by evalica** [comment] 2017-08-01 17:43
I've created this Doodle http://doodle.com/poll/b44zgm4ksm3pf5hw to see participation per days. 
Let me know if it needs improvements/refinements

**Comment by pdurbin** [comment] 2017-08-01 22:51
As I mentioned on the [Monthly Open Source Design call](https://discourse.opensourcedesign.net/t/monthly-open-source-design-call/253) today, I'm not sure if I can make it to the summit. If my JavaOne talk is accepted, I'll be in San Fransisco instead. If my JavaOne talk **isn't** accepted, I still need to figure out if there's funding for me to travel to Berlin. Sorry to be so squishy. I should know if my JavaOne talk has been accepted or not soon. It was great putting names with faces today on the call!

**Comment by belenbarrospena** [comment] 2017-08-08 17:45
I've updated the Doodle poll. I expect to be there over the weekend, although there is a chance I might be able to stay for the whole thing. We'll see :)

About sessions, I would like to spread the word about Open Source Design between what I call (for lack of a better word), the "mainstream" design community. The idea would be identifying key design conferences (UXPA, IA Summit, EuroIA, Interaction, etc), create a presentation about us, what we do and why it's important, and then submit it. A skeleton for a workshop about design in open source that we could also submit to these conferences would be good as well.

**Comment by pdurbin** [comment] 2017-08-09 02:00
I just found out that my [talk][] in San Francisco was accepted (yay!) so I definitely won't be able to attend the Open Source Design Summit because I can't be away from my kids and family for too long. I hope the summit is a great success and that I can attend next year!

[talk]: http://wiki.greptilian.com/talks/2017/javaone-how-to-run-an-open-source-project

**Comment by simonv3** [comment] 2017-08-09 03:23
Congrats @pdurbin! Sorry to hear it, but makes sense :)

**Comment by jancborchardt** [comment] 2017-08-17 09:25
@simonv3 @evalica can you also fill out the doodle? :) Also cc @victoria-bondarchuk @bnvk @Incabell @jdittrich @mkfnch

**Comment by simonv3** [comment] 2017-08-17 16:46
Done! I'm pretty blank on topics at the moment. Kind of just want to do a workshop / brainstorm / hack session on revamping our website.

**Comment by ei8fdb** [comment] 2017-08-17 22:30
This is a pity for us but a great thing for you. I hope the talk goes
really well. Hope to see you next year.

**Comment by evalica** [comment] 2017-09-05 17:14
Small status / planning session for FOSDEM

**Comment by evalica** [comment] 2017-09-05 17:14
Introductions session / Status for OSD community (at the beginning)

**Comment by evalica** [comment] 2017-09-05 17:16
Unconference / Brainstorming about what we want to discuss at the Summit

**Comment by jdittrich** [comment] 2017-09-05 17:18
**Talk/Discussion Proposal:** UX debt and why it is a particular problem for open source projects.
**Description:** UX debt is the equivalent to [technical debt](https://en.wikipedia.org/wiki/Technical_debt): Incoherence of approaches, lack of internal standards, quickly implemented, but not clean additions. Same exists for UX. The trouble is that UX debt is exposed to the user: In contrast to code it can't the refactored unnoticed.

**Comment by tessgadwa** [comment] 2017-09-05 17:18
@jancborchardt @jdittrich I'd be interested in talking about structural and systemic issues affecting usability and FOSS. Wondering if a "best practices for UX in open source" might be better as a collaborative session for an unconference and/or workshop.

**Comment by evalica** [comment] 2017-09-05 17:25
Lunch / Dinner planning (time)

**Comment by cameralibre** [comment] 2017-09-07 07:37
I would like to run a 1-2 hour version of an 'analog open source collaboration' workshop like the one I've proposed for Mozfest: [Cut, Copy & Paste: Use (analog!) open source collaboration to make your own MozFest Zine](https://github.com/MozillaFoundation/mozfest-program-2017/issues/472). 

The primary aim would be for us to invite some non-open-source designer friends to come and co-create with us, to get to grips with the open source methodology and how it can be  so interesting, practical and creative. (As I see it, more designers with an understanding of open source are required in order to get more designers working on open source software)

The secondary aim would be to prototype and improve the workshop itself, with the knowledge and insight of open source designers, in order to make it a useful open source educational module which others can use.

**Comment by digitigrafo** [comment] 2017-09-07 08:10
hi, I'll be in Berlin at the summit on 16 and 17 of october. I like to do a small talk about "Redesign comment platform". I'm involved in this project http://www.scholio.net/ and I like to share the info that I  collected about: which are the commons problems, what propose critical thinking, cases of study. thanks

**Comment by simonv3** [comment] 2017-09-07 16:30
@digitigrafo I think the actual talk days will probably be the 14th or 15th, will you be in Berlin one of those days? It'd be great to hear it if you are!

**Comment by pkruithofjr** [comment] 2017-09-07 18:49
Excited to know there is an open-source event!

Unfortunately, I'm taking a few courses at the Nielsen|Norman UX Conference in Chicago until October 13th and likely unable to attend (although flights are not terribly expensive.) 

Two collaborators and I are proposing a talk at the UXPA annual conference in Puerto Rico on user experience within the OpenStack community, but it hasn't been reviewed for acceptance as a session.

**Comment by tessgadwa** [comment] 2017-09-07 19:02
I'd like to present a talk / Q&A on the following topic:

* Systemic and Structural Challenges for the Open Source Design Community *

This talk will cover some of the economic and organizational barriers to
full participation by designers and ux professionals with the FOSS world.
For example, designers typically earn a lower hourly rate than programmers
and may have less free time to give to projects. In addition, large FOSS
projects staffed entirely or partially by volunteers may not have adequate
time or resources to collaborate with non-programmers. It will also discuss
the need for moving beyond purely cosmetic types of design (e.g. logo,
website redesign) and into the essential work of interaction design and
product design. The goal of this talk is to take an incremental approach to
problem solving -- recognizing that while there is rarely a "silver bullet"
solution that will resolve systemic issues overnight, there are a number of
smaller actions and best practices that we can adopt and urge others in our
community to adopt. The end goal is a more resilient, inclusive community
that truly reflects the values of open source.


I would love to reserve time for open discussion following this talk as
well.


-- 


Tess Gadwa

Chief Executive Officer
_______________________________

Yes Exactly, Inc. | yesexactly.com | 413.325.8251

**Comment by digitigrafo** [comment] 2017-09-07 19:13
On 07.09.2017 18:30, Simon wrote:
>
> @digitigrafo <https://github.com/digitigrafo> I think the actual talk
> days will probably be the 14th or 15th, will you be in Berlin one of
> those days? It'd be great to hear it if you are!
>
no sorry, I'll arrive in berlin 15th night.

**Comment by pkruithofjr** [comment] 2017-09-07 19:14
This is our proposal to UXPA:

*Open to whom?: An overview of the evolution of open-source software and how users are impacted*

This presentation will include a portrayal of the OpenStack open-source community, which includes a discussion of the differences in how software development is driven within open-source communities versus traditional enterprise environments. 

In addition, there will be a discussion of specific tactics used to help drive and formalize user experience within the OpenStack community. This includes a focus on gaining credibility within the community and providing concrete design work on which others can build. 

Finally, the presentation will include several examples of user research projects completed on behalf of the OpenStack community that demonstrate the success of the tactics presented.

**Comment by pkruithofjr** [comment] 2017-09-07 19:20
BTW. Excited to have discovered this group!

**Comment by belenbarrospena** [comment] 2017-09-26 18:40
I joined the weekly call today. It was just me and @tessgadwa 

We had a very interesting conversation about FOSDEM and other various things :)

She had some feedback for us regarding how little information is available in [the Summit page](http://opensourcedesign.net/summit/). She suggested adding some information about the programme there.

I haven't been much in touch with the Summit organisation stuff, but I believe venues have been confirmed. What about the programme? Is the plan to have an unconference-type of thing over the weekend?

**Comment by simonv3** [comment] 2017-09-26 20:20
That's my understanding, though people have already started suggesting things and making proposals for things here.

**Comment by h-nes** [comment] 2017-10-03 19:28
hello everyone,

i want to participate Sat + Sun (Sun most likely only the morning - hope there are sessions scheduled?)

Besides some occasional involvement during my regular job with the open source world, I'm quite new to the FOSS community. I will bring my professional background as a design lead at IXDS but unfortunately not in a presentable format/talk. My main question seems to be very much covered by @tessgadwa's [session](https://github.com/opensourcedesign/organization/issues/95#issuecomment-327893758).

**Comment by simonv3** [comment] 2017-10-04 00:55
I'll be making up a schedule based on the initial submitted talks and workshops. I thought it would make sense to have talks generally on Sunday morning and to use saturday morning for getting to know each other, game storming some things, some "tell us about your projects" kind of events, and maybe using saturday afternoon as a workshop, go work on specific things kind of afternoon. Sunday afternoon would be for continuing those workshops!

If that generally sounds good with folks I'll throw up an outline.

**Comment by jancborchardt** [comment] 2017-10-04 13:09
@simonv3 sounds great! :) Thank you!

**Comment by pdurbin** [comment] 2017-10-04 16:10
> I just found out that my talk in San Francisco was accepted (yay!) so I definitely won't be able to attend the Open Source Design Summit

I just thought I'd mention that I gave my talk last night and mentioned Open Source Design on slide 7:

<img width="650" alt="screen shot 2017-10-04 at 9 01 54 am" src="https://user-images.githubusercontent.com/21006/31186232-f08c2bec-a8e2-11e7-9000-0ca64a16d4cb.png">

You can download the slides from https://twitter.com/philipdurbin/status/915607171097702400

Also, went to another talk called [Boost Your Skills with Open Source](https://events.rainfocus.com/catalog/oracle/oow17/catalogjavaone17?search=CON2691) and I mentioned Open Source Design to @bartoszmajsak and he said he'd try to add it to his slides in the future. One of his and @tombujok 's slides had a picture of paintbrushes on it and they talked about design.

**Comment by evalica** [comment] 2018-02-07 14:29
Closing since the event has passed!

**Closed by evalica** 2018-02-07 14:29 UTC
Labels: summit

**Comment by dimitrieh** [comment] 2018-02-07 15:01
Event was great!! 👍
