### ISSUE TITLE
Hosting visitors for Open Source Design Summit

### ISSUE THREAD

**Issue by jdittrich** [opensourcedesign/organization#96] opened 2017-09-05 17:45 UTC
This ticket is for requesting and/or offering a place to sleep in Berlin – for fun and/or because a hotel is too €€€ e.g. for students or so.

**Comment by evalica** [comment] 2017-10-09 11:01
Duplicate of https://github.com/opensourcedesign/organization/issues/65 
Also check https://github.com/opensourcedesign/organization/issues/97#issuecomment-335115032

**Comment by evalica** [comment] 2018-02-07 14:29
Closing since the event has passed!

**Closed by evalica** 2018-02-07 14:29 UTC
Labels: summit
