### ISSUE TITLE
OSD Summit Schedule

### ISSUE THREAD

**Issue by elioqoshi** [opensourcedesign/organization#66] opened 2017-03-03 12:17 UTC
Let's talk about how long the OSD Summit should be. 

So I'd propose a fully fledged version and a more lightweight one. We can decided based on the availability of most people.

## Extended
Friday: Arrival. Welcome Dinner. Light Reception Drinks.
Saturday: Working Day 1 on Core OSD Roadmap for 2018
Sunday: Working Day 2 on wrapping up stuff from day 1 and fixing blockers. Afterparty
Monday: Public Hacking Day. Post New jobs. Work on the jobs section. 
Tuesday: Departure / Sightseeing and social activities in the city.
Wednesday: Departure

## Lightweight
Friday:  Arrival. Welcome Dinner. Light Reception Drinks.
Saturday:  Working Day 1 on Core OSD Roadmap for 2018
Sunday:  Public Hacking Day. Work on the Jobs section. Social Activities in the evening
Monday: Departure

An alternative would be to go with the first plan and those who cannot commit for all days, stay for the most important days only.

What do you think?

**Comment by jancborchardt** [comment] 2017-03-03 12:27
Depending on when most people are there, we should make th core sessions on Saturday, as most people will probably arrive on Friday at the latest and leave Sunday evening earliest.

I think both plans are good, only that I think »Post new jobs« and _especially_ »Polish site« and »Polish job board« is way more important than »Wrap up jobs«. :) We need to think in the big picture here.

**Comment by elioqoshi** [comment] 2017-03-03 12:45
@jancborchardt right, let's avoid micromanaging.

I updated the first proposal with what you suggested:

## Extended
Friday: Arrival. Welcome Dinner. Light Reception Drinks.
Saturday: Working Day 1 on Core OSD Roadmap for 2018
Sunday: Working Day 2 on wrapping up stuff from day 1 and fixing blockers. 
Monday: Public Hacking Day. Post New jobs. Work on the jobs section. Promote Open Collective in our Networks. Afterparty
Tuesday: Departure / Sightseeing and social activities in the city.
Wednesday: Departure

**Comment by simonv3** [comment] 2017-03-03 17:17
I vote for the extended version.

**Comment by bnvk** [comment] 2017-03-03 18:02
> I vote for the extended version.

I also. Due to costs, environmental impact, getting everyone in one place, 
etc.. make the most of it

**Comment by elioqoshi** [comment] 2017-03-03 18:04
If it was not clear, I vote for Extended as well.

Just to clarify, also those who cannot stay on all dates are welcome to come by for as many as they can of course I guess

**Comment by evalica** [comment] 2017-03-03 21:40
I would be able to attend for max 3 days, so I will let you guys vote on the version and I'll try to see how I can make it happen.

**Comment by victoria-bondarchuk** [comment] 2017-03-03 21:48
Same as @evalica, not sure that would be able to attend Extended version, but for sure can make it for 3 days.

**Comment by elioqoshi** [comment] 2017-03-03 22:51
Great! From what I see, Mon 10/16 – Sun 10/22 seems to be the week everyone apart @Xaviju can make it. I hope you will still be able to come, let us know if we can help :)

Did we forget anyone else?
Now there is another slight problem: Will the schedule start from the Friday 13th (no pun intended) or Friday 20th? So will we overlap with the week before or the week after? We haven't thought that out when doing the doodle it seems.

**Comment by elioqoshi** [comment] 2017-03-03 22:54
From the voting, it seems that the week before would make more sense. So the schedule for the extended version would be like:

##Extended
13th Friday: Arrival. Welcome Dinner. Light Reception Drinks.
14th Saturday: Working Day 1 on Core OSD Roadmap for 2018
15th Sunday: Working Day 2 on wrapping up stuff from day 1 and fixing blockers. Afterparty
16th Monday: Public Hacking Day. Post New jobs. Work on the jobs section.
17th Tuesday: Departure / Sightseeing and social activities in the city.

Thoughts?
18th Wednesday: Departure

**Comment by belenbarrospena** [comment] 2017-03-04 10:54
Same as @evalica and @victoria-bondarchuk : I might not be able to attend the whole thing, but hopefully I'll make it for some of it.

**Comment by elioqoshi** [comment] 2017-03-06 11:38
Can we get some thoughts on the dates? 13-18th October that is. With 14 & 15 being the core working days.

**Comment by jancborchardt** [comment] 2017-03-07 14:39
It’s fine with me.

@evalica @victoria-bondarchuk @bnvk @belenbarrospena @simonv3 @Kriesse @gsambrotta what do you think?

**Comment by jancborchardt** [comment] 2017-03-07 14:40
It’s fine with me.

@evalica @victoria-bondarchuk @bnvk @belenbarrospena @simonv3 @Kriesse @gsambrotta @eppfel @Xaviju @ei8fdb what do you think? :)

**Comment by jancborchardt** [comment] 2017-03-07 18:11
So we should have the core content on Saturday, then Sunday a bit more. Afterwards mostly hacking and working on what was discussed. :) We used that format at the Nextcloud conference and it works quite well.

**Comment by jancborchardt** [comment] 2017-03-07 18:34
Some proposed agenda items / working groups for the hack days:
- Website design improvements
- Job board flow improvements
- Writing some articles
- A nicer resources site
- Site for showcasing some well-designed open source projects
- Local meetup organization
- Coordination of gettings involved in other confs (also design conferences)
- Pre-planning of FOSDEM
- Pre-planning of next years Open Source Design Summit
- …

**Comment by jancborchardt** [comment] 2017-06-06 18:21
We just talked about it in the call again and we need to specify what the summit is for. In general it is more for pushing Open Source Design as an organization, and getting all designers working in open source together. It is _less_ for doing design jobs of a specific project, it is about exchange. :)

It would be best if we put these rough ideas what we can talk about on the summit website, as well as also roughly saying that Sat/Sun will be unconference/barcamp days and Monday/Tuesday will be "working" days (however we want to define it). :)

cc @eppfel @jdittrich @Incabell @evalica @bnvk @simonv3

**Comment by dimitrieh** [comment] 2017-06-20 07:11
> We just talked about it in the call again and we need to specify what the summit is for. 

@elioqoshi @eppfel @jdittrich @Incabell @evalica @bnvk @simonv3 @jancborchardt Reaching out for GitLab UX team here. We are actively discussing this OSD event internally and if we want/can attend 😄 . However we would like to know some more specifics on what the event is actually about/for.

It seems a great deal is about moving the organisation & website forward, which is great, but we are not sure if that is the right fit for multiple of us attending. Just throwing some idea's out here, but we were thinking more in terms of having a day with some speaker sessions in there. Sharing on design topics such as:
- Open Source Design - Goals, Culture, Values etc (primer into why we are here)
- Open source and its influence on Design
- Design Discussion - Exploration/Direction Sprinting and Defining MVP's
- UX Research - Finding and Validating - Persona's, Quantitative & Qualitative research
- Design within Organisations - Balance, position and influence within organisations
- Direction of design tooling - How are tools empowering our workflows
- Design management - Leading UX efforts

After which discussion and intermingling can begin.

We would probably be able to do a speaker session on one or multiple of those topics, as to share the vision and idea's GitLab has. However we would need others as well of course!

Would love to know some thoughts on this. Does this resonate with what you have in mind for this summit? Etc. So we are able to discuss this in our internal meeting next Tuesday (2017-06-27) 😉

**Comment by jancborchardt** [comment] 2017-06-20 15:13
@dimitrieh that would be great! :) Since we have 4 days (with 2 core days) there should be plenty of space to accomodate this.

And in general if you have speakers for these topics, please also make sure to hand them in at our next Open Source Design track, for example at FOSDEM or FOSSASIA. :)

**Comment by dimitrieh** [comment] 2017-06-27 20:47
Hi I wanted to leave the following statement: We (ux team at GitLab) decided that this is for now not yet the right event to go to as a complete team. We reached this decision as this event is more focussed on brainstorming how to proceed with the open source foundation rather than discussing and talking about the topics suggested in my previous comment. We collectively wish everyone the best of times of course, and may "open source design" reach new heights because of it! 💯 

In the coming week I am going to look if it's a viable option for myself to visit though :).

**Comment by jdittrich** [comment] 2017-06-27 21:11
@dimitrieh Thanks for letting us know. Pity, I would have loved to have the conversations you suggested! (particularly Research and tools) 

(Alternatively, though not as nice as real life: [our discourse](https://discourse.opensourcedesign.net/))

**Comment by tessgadwa** [comment] 2017-06-27 21:12
When and where is the Summit?

**Comment by simonv3** [comment] 2017-06-28 15:09
@tessgadwa It's going to be in Berlin the week of the 13th to the 18th. 

Everything that's been decided so far is on the website: http://opensourcedesign.net/summit/

Weren't we settling on an unconference direction where attendees could decide what they wanted to focus on? (with some general structure and themes decided beforehand?)

**Comment by tessgadwa** [comment] 2017-06-28 19:15
Thanks. Agenda looks great so far. I'm in USA (Pacific Coast) but if I can, I'll try to make it out there...

**Comment by tessgadwa** [comment] 2017-06-28 19:37
@dimitrieh the topics below seem to me like they would be a good fit.

Open Source Design - Goals, Culture, Values etc (primer into why we are here)
Open source and its influence on Design
Design Discussion - Exploration/Direction Sprinting and Defining MVP's
UX Research - Finding and Validating - Persona's, Quantitative & Qualitative research
Design within Organisations - Balance, position and influence within organisations
Direction of design tooling - How are tools empowering our workflows
Design management - Leading UX efforts

**Comment by tessgadwa** [comment] 2017-06-28 20:02
also invite anyone and everyone to contribute to the discussion and also share info about this conference on https://riot.im/app/#/room/#designUX:matrix.org

**Comment by jancborchardt** [comment] 2017-06-28 23:02
@tessgadwa we already use the channel #opensourcedesign also :) But yes, please spread the info about the conference!

@dimitrieh hm, that's a bummer. It is an unconference where everyone contributes to the program, so it would be cool if at least one of you can make it. :) But yes in any case please join our forum at https://discourse.opensourcedesign.net as @jdittrich mentioned.

**Comment by tessgadwa** [comment] 2017-07-11 17:30
Is the Berlin Summit confirmed and happening for sure? Would like to purchase plane tix.

**Comment by simonv3** [comment] 2017-07-11 20:23
As far as I'm concerned it's definitely happening. I'm planning my October travels around it (but I also have other reasons to be in Europe, so there's that)

**Comment by jancborchardt** [comment] 2017-07-16 20:52
Yup, same here! :)

Please do RSVP / get a ticket using the OpenCollective functionality @simonv3 posted about: https://discourse.opensourcedesign.net/t/open-collective-event-for-summit/245 so we can gauge how many people are interested.

**Comment by tessgadwa** [comment] 2017-07-16 21:06
Ticket purchased!

**Comment by pdurbin** [comment] 2017-07-29 15:11
With input from @jancborchardt I just created pull request https://github.com/opensourcedesign/events/pull/79 which contains the summit schedule as I understand it. Does it look right?

I'd love to come but it depends a lot of if my talk for an event in San Francisco for early October is accepted or not. I can only be away from my kids so long.

**Comment by dimitrieh** [comment] 2017-07-31 19:45
I just booked my ticket and lodging for Berlin and will be joining the event on the 18th! Will look forward to join you guys for a day! Excited to meetup, learn and see how things will progress for the open source design foundation/organisation. 

Will try to dive somewhat deeper in all the content here in the coming days/weeks 😉

**Comment by tessgadwa** [comment] 2017-07-31 19:47
Sweet! Do you know about tomorrow's call?

**Comment by dimitrieh** [comment] 2017-07-31 19:50
@tessgadwa no i don't :) would be happy to join, although i have quite some meetings every tuesday.. can you refer me to a place with more info on that?

**Comment by tessgadwa** [comment] 2017-07-31 19:54
Here's the info:
http://opensourcedesign.net/events/open-source-design-monthly-online-meeting/

**Comment by dimitrieh** [comment] 2017-07-31 20:18
@tessgadwa cool, thanks. Will try to see if I can join tomorrow! 😉

**Comment by HeikoTietze** [comment] 2017-07-31 21:04
Will join the OSD summit on Sunday, latest to the after party, as the LibreOffice conference ends on Saturday.

**Comment by jancborchardt** [comment] 2017-09-05 18:07
Please also make sure to
- comment in the thread on Open Source Design Summit attendance & actual session proposals #95
- answer in the Doodle http://doodle.com/poll/b44zgm4ksm3pf5hw to see participation per days
- RSVP / get a ticket on the Open Collective page: https://opencollective.com/opensourcedesign/events/opensourcedesign-summit (tickets are unlimited, just to see how many people will come :)

**Comment by evalica** [comment] 2017-10-09 11:03
Related to https://github.com/opensourcedesign/organization/issues/95

**Comment by simonv3** [comment] 2017-10-09 17:56
## Proposed Schedule:

Time: | Saturday | Sunday 
-- | --------| --------
10:00 - 12:00 | Introductions, what you been up to? Petcha Kutcha style. | Talks!
12:00 - 13:00 | Lunch | Lunch
13:00 - 13:30 | Unconference workshop proposal time (suggest workshops, voice interest in workshops) | Unconference workshop proposal time
13:30 - 15:00 | Workshops 1 | Workshops 3
15:00 - 16:30 | Workshops 2 | Workshops 4
Evening | Dinner? | Dinner? 

Let me know what you think!

**Comment by dimitrieh** [comment] 2017-10-10 11:43
Where is the schedule for wed 18th, if any? :)

**Comment by simonv3** [comment] 2017-10-10 15:28
@dimitrieh I won't be there on the 18th, and had been under the impression that the organized activities would be happening on the weekend and that the following days would be much less structured and dependent on the stuff that gets done on the weekend. 

cc @jancborchardt any ideas?

**Comment by rasmusskjoldan** [comment] 2017-10-13 20:27
Hey. I was hoping to join on the last day - but it seems only "departure" is planned for Wednesday :-) I will be in Berlin though. Does anything else happen that day? Otherwise hit me, if we can meet anyway.

**Comment by evalica** [comment] 2018-02-07 14:30
Closing since the event has passed!

**Closed by evalica** 2018-02-07 14:30 UTC
Labels: discussion, summit
